package db

func Countries() []Country {
	return []Country{
		{"Andorra", "AD"},
		{"Albania", "AL"},
		{"Armenia", "AM"},
		{"Austria", "AT"},
		{"Belgium", "BE"},
		{"Bulgaria", "BG"},
		{"Switzerland", "CH"},
		{"Cyprus", "CY"},
		{"Czechia", "CZ"},
		{"Germany", "DE"},
		{"Denmark", "DK"},
		{"Estonia", "EE"},
		{"Greece", "EL"},
		{"Spain", "ES"},
		{"Finland", "FI"},
		{"France", "FR"},
		{"Georgia", "GE"},
		{"Croatia", "HR"},
		{"Hungary", "HU"},
		{"Ireland", "IE"},
		{"Iceland", "IS"},
		{"Italy", "IT"},
		{"Liechtenstein", "LI"},
		{"Lithuania", "LT"},
		{"Luxembourg", "LU"},
		{"Latvia", "LV"},
		{"Montenegro", "ME"},
		{"Malta", "MT"},
		{"Netherlands", "NL"},
		{"Norway", "NO"},
		{"Poland", "PL"},
		{"Portugal", "PT"},
		{"Romania", "RO"},
		{"Serbia", "RS"},
		{"Sweden", "SE"},
		{"Slovenia", "SI"},
		{"Slovakia", "SK"},
		{"United Kingdom", "UK"},
	}
}
